import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

// User-facing endpoint: sends the provide summary text to the user's email
export async function POST(request: NextRequest) {
    try {
        const supabase = await createClient();
        const { data: { user } } = await supabase.auth.getUser();
        if (!user || !user.email) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

        const { summary } = await request.json();
        if (!summary) return NextResponse.json({ error: 'Missing summary content' }, { status: 400 });

        const fullName = user.user_metadata?.full_name || 'there';
        const firstName = fullName.split(' ')[0];

        const { error } = await resend.emails.send({
            from: 'Cerebro Digest <onboarding@resend.dev>',
            to: 'abdallahabdelnbii467@gmail.com', // Overriding user.email to bypass unverified Resend domain limit for local development
            subject: `🧠 ${firstName}'s Daily Cerebro Summary`,
            html: `
        <div style="font-family: Inter, sans-serif; max-width: 600px; margin: 0 auto; background: #0A0712; color: #F0F4FF; padding: 40px 24px; border-radius: 20px; border: 1px solid rgba(255,255,255,0.05);">
          <div style="display: flex; align-items: center; gap: 12px; margin-bottom: 32px;">
            <div style="width: 40px; height: 40px; background: linear-gradient(135deg, #0EA5E9, #F59E0B); border-radius: 12px; display: flex; align-items: center; justify-content: center; font-size: 20px;">🧠</div>
            <span style="font-size: 24px; font-weight: 700; background: linear-gradient(to right, #F0F4FF, #818CF8); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">Cerebro</span>
          </div>
          
          <h2 style="color: #F0F4FF; margin-bottom: 20px; font-family: 'Outfit', sans-serif; font-weight: 600;">Today's Personal Digest for ${firstName}</h2>
          
          <div style="background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.08); border-left: 4px solid #F59E0B; border-radius: 16px; padding: 24px; white-space: pre-wrap; line-height: 1.8; color: #D1D5DB; font-size: 15px;">
${summary}
          </div>
          
          <div style="margin-top: 32px; text-align: center;">
            <a href="${process.env.NEXT_PUBLIC_APP_URL || 'https://cerebro.app'}/dashboard" style="display: inline-block; background: linear-gradient(135deg, #0EA5E9, #0369A1); color: white; padding: 14px 28px; border-radius: 12px; text-decoration: none; font-weight: 600; font-size: 14px; box-shadow: 0 4px 20px rgba(14,165,233,0.3);">Open Dashboard →</a>
          </div>
          
          <p style="text-align: center; color: rgba(255,255,255,0.4); font-size: 12px; margin-top: 32px;">
            This summary was generated by Cerebro AI based on your recent activity. 
            <br/>
            <a href="${process.env.NEXT_PUBLIC_APP_URL || 'https://cerebro.app'}/settings" style="color: #818CF8; text-decoration: none;">Manage preferences</a>
          </p>
        </div>
      `,
        });

        if (error) {
            return NextResponse.json({ error: error.message }, { status: 400 });
        }

        return NextResponse.json({ success: true });
    } catch (error: unknown) {
        const errMsg = error instanceof Error ? error.message : 'Unknown error';
        return NextResponse.json({ error: errMsg }, { status: 500 });
    }
}
