import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

// User-facing endpoint: sends the provide summary text to the user's email
export async function POST(request: NextRequest) {
    try {
        const supabase = await createClient();
        const { data: { user } } = await supabase.auth.getUser();
        if (!user || !user.email) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

        const { summary } = await request.json();
        if (!summary) return NextResponse.json({ error: 'Missing summary content' }, { status: 400 });

        const fullName = user.user_metadata?.full_name || 'there';
        const firstName = fullName.split(' ')[0];

        const appUrl = 'https://notegraph.online';
        const fromEmail = process.env.RESEND_FROM_EMAIL || 'NoteGraph <noreply@notegraph.online>';

        const { error } = await resend.emails.send({
            from: fromEmail,
            to: user.email,
            replyTo: 'noreply@notegraph.online',
            subject: `Your Daily NoteGraph Summary - ${firstName}`,
            headers: {
                'List-Unsubscribe': `<${appUrl}/settings>`,
                'List-Unsubscribe-Post': 'List-Unsubscribe=One-Click',
                'X-Entity-Ref-ID': user.id,
            },
            html: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your NoteGraph Summary</title>
</head>
<body style="margin:0;padding:0;background:#f4f4f5;font-family:'Inter',-apple-system,BlinkMacSystemFont,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f5;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background:#09090b;border-radius:16px;overflow:hidden;border:1px solid #27272a;">
          <!-- Header -->
          <tr>
            <td style="padding:32px 40px 24px;border-bottom:1px solid #27272a;">
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td>
                    <span style="font-size:20px;font-weight:700;color:#f4f4f5;">NoteGraph</span>
                  </td>
                  <td align="right">
                    <span style="font-size:12px;color:#71717a;">Daily Summary</span>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- Greeting -->
          <tr>
            <td style="padding:32px 40px 0;">
              <h1 style="margin:0 0 8px;font-size:22px;font-weight:700;color:#fafafa;">Hi ${firstName},</h1>
              <p style="margin:0;font-size:14px;color:#a1a1aa;">Here is your personalized knowledge digest for today.</p>
            </td>
          </tr>
          <!-- Summary body -->
          <tr>
            <td style="padding:24px 40px;">
              <div style="background:#18181b;border-left:3px solid #0ea5e9;border-radius:8px;padding:24px;white-space:pre-wrap;line-height:1.8;color:#e4e4e7;font-size:15px;">
${summary}
              </div>
            </td>
          </tr>
          <!-- CTA -->
          <tr>
            <td style="padding:0 40px 32px;text-align:center;">
              <a href="${appUrl}/dashboard" style="display:inline-block;background:#0ea5e9;color:#ffffff;padding:12px 32px;border-radius:8px;text-decoration:none;font-weight:600;font-size:14px;">View Dashboard</a>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="padding:24px 40px;border-top:1px solid #27272a;text-align:center;">
              <p style="margin:0;font-size:12px;color:#52525b;">Generated by NoteGraph AI from your recent notes.</p>
              <p style="margin:8px 0 0;font-size:12px;color:#52525b;">
                <a href="${appUrl}/settings" style="color:#71717a;">Manage email preferences</a>
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`,
        });

        if (error) {
            return NextResponse.json({ error: error.message }, { status: 400 });
        }

        return NextResponse.json({ success: true });
    } catch (error: unknown) {
        const errMsg = error instanceof Error ? error.message : 'Unknown error';
        return NextResponse.json({ error: errMsg }, { status: 500 });
    }
}
